name: asif
on:
    push: 
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          uses: actions/checkout@v4
        - name: a
          run: echo checking my custom action
        - name: am putting my first docker custom action to marketplace
          uses: asif741852014/myfirst@v1.0.13
